### ISSUE TITLE
Option to phase to the tile beam center rather than raphase/decphase if no phasing done in MWAX

### ISSUE THREAD

**Issue by bhazelton** [MWATelescope/Birli#10]
Many if not all of the EoR analyses that use uvfits as a starting place have historically wanted uvfits to be phased to the tile beam center NOT the raphase/decphase. It would be good to have this as an easily set option, rather than only happening if those keywords do not exist.

**Comment by derwentx** [comment]
Hey @bhazelton , thanks for the issue! 

The plan is to get Birli to feature parity with Cotter as soon as we can, and this includes allowing users to specify whether their geometric corrections are applied to the phase center, pointing center or an arbitrary ra/dec, like cotter's `-centre <ra> <dec>` and `-usepcentre` flags.

Unfortunately, even though this is clearly a useful feature, there are several other features that have been given higher priority. To give everyone more transparency over our priorities, I've created a [github project mirror](https://github.com/MWATelescope/Birli/projects/1#card-73186246) of our internal JIRA. As you can see, it's unlikely we'll be able to get there very soon, but I'll bring this up at our next project meeting.

The way geometric corrections work at the moment is it reads the phase center from the metafits, if it can't read the phase center, it uses the pointing center, so I guess you have a couple of options:

- run Birli on a modified metafits with the phase center keyword removed or changed to the value of the tile pointing center
- use a tool like wsclean's `chgcentre` or pyuvdata to re-phase the data

Finally, there's always the option of convincing someone to implement this in Birli sooner. It would be an easy first issue, it should just be a matter of adding an extra parameter to [correct_geometry](https://github.com/MWATelescope/Birli/blob/5946efed768e7f1c927746b6f43a13d07e966f0b/src/corrections.rs#L197) and exposing the extra CLI args. I'm happy to support anyone who wants to implement this themself.

Cheers!

**Comment by bhazelton** [comment]
Thanks for the update! My group is working on getting a pyuvdata reader for the MWAX files, we actually have a PR in progress which will have this functionality. So I think that's our short-term path. But I'd really like to be able to compare what we come up with to birli outputs and I know others who'd like this functionality to be available via ASVO, which I think means it needs to be in birli (but maybe I misunderstand that).

**Comment by derwentx** [comment]
That's correct, when the new version of ASVO that we're working on is released, it will let  you choose between Birli and Cotter for processing the data, so for legacy (non-MWAX) you'll still be able to do arbitrary phase center, but there could be a brief window of time where this is not available for MWAX data, since only Birli is able to process these obs.

**Comment by derwentx** [comment]
Hey @bhazelton , this option has been added to Birli now. I can't speak for ASVO, but it's likely that the phase centre configuration options for Birli, when released will be roughly the same as they are currently with the Cotter.
