### ISSUE TITLE
Non-contiguous coarse bands could be better supported.

### ISSUE THREAD

**Issue by d3v-null** [MWATelescope/Birli#13]
Currently the only way to process non-contiguous coarse band observations in Birli is to separately process each contiguous group of coarse bands. The uvfits spec does allow for a `FQ` table which stores information about spectral windows, and pyuvdata does support reading this, so it would be testable. 

Looking for an owner for this ticket, so if there is anyone out there who particularly wants to have all the channels of their picket-fence MWAX observations in one file, please let me know. Cotter never did this, so it seems like people doing these obs must have workarounds. 

Additional discussion in #9

**Comment by gsleap** [comment]
@derwentx yeah, I think the best way to support non-contiguous coarse bands is do what cotter did and just iterate over each contiguous band instead of all 24 channels. So if the job is to output uvfits, then if there are 4 contig. bands, then there will be 4 uvfits files produced.

**Comment by doberoi** [comment]
Hi Folks, we just downloaded some non-contiguous band MWAX data from the ASVO. It showed up as a single MS with data from all of the (non-contiguous) coarse channels labelled as a single contiguous spectral window (spw). Only the first (lowest) non-contiguous band was labelled correctly. 

This is the standard observing mode for us solar folks (sorry for not engaging earlier :( ). So wanted to get a sense for the plans for fixing this... will be done at the ASVO end (by including a way to convey the details of the non-contiguous band which Birli will understand this and run iteratively) or within Birli (Birli will always check for non-contiguous bands and run iteratively) or will we always need to download visibilities and run Birli locally ?

**Comment by d3v-null** [comment]
Thanks @doberoi , 

Could you elaborate on what you mean by "Only the first (lowest) non-contiguous band was labelled correctly." 

we'll be working on supporting picket fence observations soon, the plan is to emulate Cotter's behavior, which creates multiple separate measurement sets for each contiguous set of coarse channel bands.

Until then, the recommended way of processing picket fence observations with Birli is to call Birli multiple times with groups of contiguous coarse channels.

e.g. if your raw files are

```
obs.metafits
obs_ch100.fits
obs_ch101.fits
obs_ch102.fits
obs_ch110.fits
obs_ch111.fits
obs_ch112.fits
```

you can call Birli twice

```
birli --metafits obs.metafits obs_ch{100..102}.fits --ms-out obs_ch100-102.ms
birli --metafits obs.metafits obs_ch{110..112}.fits --ms-out obs_ch110-112.ms
```

**Comment by doberoi** [comment]
Thanks @d3v-null for the prompt response and the suggested solution. Emulating Cotter's behaviour will be a perfectly acceptable solution for us. It would be great if the ASVO could also offer the support to run Birli on non-contiguous data.

Let me borrow your example to explain what I meant by my not so well worded statement. If the raw files are as you have listed them and the ch###s are organised in ascending order of observing frequency. Then the frequency labels are correct for the data from obs_ch{100..102}.fits and incorrect for all higher frequencies beyond the first non-contiguous coarse channel. Hope this helps.

**Comment by d3v-null** [comment]
Thanks for pointing this out @doberoi , 

The fact that frequencies are being incorrectly labelled is a concerning issue. We've been able to assign some developer time to work on the Cotter-style approach to picket-fence handling, which will address this issue

**Comment by doberoi** [comment]
@d3v-null Sounds great :-) Look forward to the Cotter-style fix. 

It will be really great if this functionality could also be integrated with the ASVO interface.

**Comment by d3v-null** [comment]
Non-contiguous coarse channel support has just been merged into main with https://github.com/MWATelescope/Birli/pull/134 

We've added a set of tests based on picket fence data to ensure that frequencies are correct, but I encourage you to test this for yourself.

We'll be releasing a new version of Birli shortly, which will end up in ASVO soon. Once that's done, we'll post in MWA Users Slack group.

I'll close this issue, since the fix has been merged into main, but please let us know if you have any feedback.

Thanks!
