### ISSUE TITLE
The error message produced when providing an invalid averaging value could be clearer

### ISSUE THREAD

**Issue by d3v-null** [MWATelescope/Birli#133]
This is a placeholder so that I don't forget.

An invalid averaging value was provided through asvo, and the error message just said something like "error parsing cli", but not which specific argument was at fault.

**Comment by d3v-null** [comment]
This was because the `Error` types were being printed with 

```rust
    match result {
        Err(e) => {
            eprintln!("preprocessing error: {e}")
        }
    }
```

which only showed the error type, and not the detailed error info and line number. now that it's printed with debug "{e:?}", the original error message has been restored.

```
error parsing args: CLIError(InvalidCommandLineArgument { option: "--avg-time-res <RES>", expected: "a multiple of the integration time, 0.5 [s]", received: "0.1" })
```

**Comment by cjordan** [comment]
I think printing the debug representation of the error is not what you want. If might make this particular error look OK, but most other errors will not be human readable (e.g. https://github.com/MWATelescope/Birli/commit/35e4cba23b9e3e4fa9a46213dcaeb5ba64c13d97). This is why it's called a debug rep - it's meant to be for programmers, not humans.

I therefore think that it would be best to change the `Display` method of the errors you're interested in. Alternatively, you could match on specific errors in your code block above and emit additional details there.

**Comment by d3v-null** [comment]
I agree that this would be a better solution long term, but I think including the error messages with line numbers provides a substantial improvement over just the name of the error for now. How about I open up a new ticket for this.

**Comment by d3v-null** [comment]
error looks like this now
```
error parsing args: Invalid Command Line Argument: option --avg-time-res <RES> expected a multiple of the integration time, 2 [s] but received 0.9999
```
