### ISSUE TITLE
Option to suppress stdout progress bars when using Birli as a library

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/Birli#8]
** Low Priority! **
When using Birli as a library, some methods, like `context_to_jones_array` output progress information to stdout. It would be nice to be able to suppress this output.

e.g. this is output from my binary which uses the logging crate (the log lines include dates and times, etc) but is then interspersed with std out of progress bars which I would prefer I did not see.

```
...
[2021-11-11T07:00:28Z DEBUG mwax_stats::fringes] Generating jones array...
coarse_chan 012 : [=========================================================================================================================================================================] 1   /1
loading hdus    : [00:00:00] [===========================================================================================================================================================] 100% (0s   )
[2021-11-11T07:00:28Z DEBUG mwax_stats::fringes] Jones array shape (timesteps, fine_chans, baselines)[1, 128, 8256]
...
```

**Comment by derwentx** [comment]
PR #27 closes this issue, by adding a boolean option to disable progress bars on all the methods that use them. Will be released in Birli 0.4.0 :)
